Repository prabhuignoto/react-chrono, pull requests merged in 2022-08, with the labels that each got.

#279 chore: upgrade packages
  package.json
  pnpm-lock.yaml
Labels: automerge

#281 adding new props `mediaHeight` and `classNames`
  README.md
  cypress/e2e/react-chrono/horizontal_spec.js
  cypress/e2e/react-chrono/vertical_alternating_nomedia.js
  cypress/e2e/react-chrono/vertical_alternating_spec.js
  cypress/e2e/react-chrono/vertical_spec.js
  package.json
  pnpm-lock.yaml
  src/components/GlobalContext.tsx
  src/components/timeline-elements/memoized/index.tsx
  src/components/timeline-elements/memoized/memoized-model.ts
  src/components/timeline-elements/timeline-card-content/timeline-card-content.tsx
  src/components/timeline-elements/timeline-card-media/timeline-card-media.tsx
  src/components/timeline-elements/timeline-card/timeline-horizontal-card.tsx
  src/components/timeline-elements/timeline-control/timeline-control.tsx
  src/components/timeline-elements/timeline-item-title/timeline-card-title.tsx
  src/components/timeline-vertical/timeline-vertical-item.tsx
  src/demo/vertical-samples.tsx
  src/models/TimelineCardTitleModel.ts
  src/models/TimelineModel.ts
Labels: enhancement, automerge

#282 style: fix style with border-box
  .gitignore
  src/index.css
Labels: bug, automerge

#284 chore: updates
  package.json
  pnpm-lock.yaml
Labels: automerge
